trigger:
  - master

variables:
  buildConfiguration: 'release'

pool:
 name: 'Azure Pipelines'
 vmimage: 'windows-2019'

stages:
  - stage: 'build'
    jobs:
      - job: buildJob
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              version: 5.0.x
              performMultiLevelLookup: true
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            inputs:
              command: restore

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration)'
          
  - stage: deploy
    jobs:
      - job: publishJob
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: publish
            publishWebProjects: false
            projects: '**\*.csproj'
            arguments:  '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
            zipAfterPublish: true
        - task: PublishBuildArtifacts@1
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'Azure subscription 1 (f016713d-47fd-4917-a2c7-c2805377c59c)'
            AppName: 'PipelineApps'
            package: $(Build.ArtifactStagingDirectory)/**/*.zip