trigger:
  - master

variables:
  buildConfiguration: 'release'

pool:
 name: 'Azure Pipelines'
 vmimage: 'windows-2019'

stages:
  - stage: 'build'
    jobs:
      - job: buildJob
        steps:
          - task: UseDotNet@2
            inputs: 
             version: '5.0.x'
             includePreviewVersions: true

          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              version: 5.0.x
              performMultiLevelLookup: true
              includePreviewVersions: true

          - task: DotNetCoreCLI@0
            inputs:
              command: restore

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration)'

  - stage:
    jobs:
      - job: publishJob
        steps:
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: publish
              publishWebProjects: false
              projects: '$(projectDirectory)\hadar.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: true


          - task: AzureWebApp@1
           inputs:
              azureSubscription: 'Azure subscription 1 (f016713d-47fd-4917-a2c7-c2805377c59c)'
              AppName: 'PipelineApps'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'